# Generated by Django 6.1 on 2026-08-31 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hostname", models.CharField(max_length=100, unique=True, verbose_name="主机名")),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("firewall", "防火墙"),
                            ("switch", "交换机"),
                            ("loadbalancer", "负载均衡"),
                            ("router", "路由器"),
                            ("server", "服务器"),
                        ],
                        max_length=50,
                        verbose_name="设备类型",
                    ),
                ),
                ("ip_address", models.CharField(blank=True, default="", max_length=50, verbose_name="管理IP")),
                ("remark", models.TextField(blank=True, default="", verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "idc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="assets.datacenter",
                        verbose_name="数据中心",
                    ),
                ),
            ],
            options={
                "verbose_name": "网络设备",
                "verbose_name_plural": "网络设备",
                "db_table": "devices_device",
            },
        ),
        migrations.CreateModel(
            name="DeviceConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("git_commit_hash", models.CharField(max_length=40, verbose_name="Git Commit Hash")),
                ("config_json", models.JSONField(blank=True, null=True, verbose_name="解析后的配置数据")),
                ("parse_duration", models.FloatField(blank=True, null=True, verbose_name="解析耗时(秒)")),
                ("collected_at", models.DateTimeField(auto_now_add=True, verbose_name="采集时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configs",
                        to="assets.device",
                        verbose_name="关联设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备配置",
                "verbose_name_plural": "设备配置",
                "db_table": "devices_deviceconfig",
                "ordering": ("-collected_at",),
            },
        ),
    ]
