# Generated by Django 6.1 on 2026-08-31 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_device_deviceconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='设备型号')),
            ],
            options={
                'verbose_name': '设备型号',
                'verbose_name_plural': '设备型号',
                'db_table': 'devices_devicemodel',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='厂商名称')),
                ('name_en', models.CharField(blank=True, default='', max_length=100, verbose_name='英文名')),
                ('abbr', models.CharField(blank=True, default='', max_length=20, verbose_name='缩写')),
            ],
            options={
                'verbose_name': '设备厂商',
                'verbose_name_plural': '设备厂商',
                'db_table': 'devices_vendor',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='assets.cabinet', verbose_name='所属机柜'),
        ),
        migrations.AddField(
            model_name='device',
            name='height',
            field=models.PositiveIntegerField(default=1, verbose_name='设备高度(U)'),
        ),
        migrations.AddField(
            model_name='device',
            name='security_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='assets.securityzone', verbose_name='安全区'),
        ),
        migrations.AddField(
            model_name='device',
            name='u_position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='起始U位'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('firewall', '防火墙'), ('switch', '交换机'), ('loadbalancer', '负载均衡'), ('router', '路由器'), ('server', '服务器'), ('dns', '域名解析'), ('dwdm', '波分复用'), ('internalac', '上网行为管理'), ('wirelessac', '无线控制器')], max_length=50, verbose_name='设备类型'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='assets.devicemodel', verbose_name='设备型号'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_models', to='assets.vendor', verbose_name='所属厂商'),
        ),
        migrations.CreateModel(
            name='DeviceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(blank=True, null=True, verbose_name='连接地址')),
                ('connection_type', models.CharField(choices=[('netmiko', 'Netmiko'), ('napalm', 'NAPALM'), ('paramiko', 'Paramiko'), ('ssh', 'SSH')], default='napalm', max_length=20, verbose_name='连接类型')),
                ('driver', models.CharField(blank=True, default='', max_length=50, verbose_name='驱动/平台')),
                ('port', models.PositiveIntegerField(default=22, verbose_name='端口')),
                ('account_type', models.CharField(choices=[('admin', '管理员'), ('operator', '操作员'), ('readonly', '只读用户')], default='admin', max_length=20, verbose_name='账号类型')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('enable_password', models.CharField(blank=True, default='', max_length=255, verbose_name='Enable密码')),
                ('timeout', models.PositiveIntegerField(default=30, verbose_name='连接超时(秒)')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='assets.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '设备连接',
                'verbose_name_plural': '设备连接',
                'db_table': 'devices_deviceconnection',
                'unique_together': {('device', 'account_type')},
            },
        ),
    ]
