# Generated by Django 6.1 on 2026-08-31 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_devicemodel_vendor_device_cabinet_device_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.PositiveIntegerField(unique=True, verbose_name='VLAN ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='VLAN名称')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
            ],
            options={
                'verbose_name': 'VLAN',
                'verbose_name_plural': 'VLAN',
                'db_table': 'devices_vlan',
                'ordering': ('vid',),
            },
        ),
        migrations.CreateModel(
            name='Vrf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('rd', models.CharField(blank=True, default='', max_length=50, verbose_name='RD')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': 'VRF',
                'verbose_name_plural': 'VRF',
                'db_table': 'configs_vrf',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=18, verbose_name='目的网段 (CIDR)')),
                ('nexthop', models.GenericIPAddressField(blank=True, null=True, verbose_name='下一跳地址')),
                ('interface', models.CharField(blank=True, default='', max_length=255, verbose_name='出接口')),
                ('protocol', models.CharField(choices=[('static', '静态'), ('connected', '直连'), ('ospf', 'OSPF'), ('bgp', 'BGP'), ('rip', 'RIP'), ('other', '其他')], default='static', max_length=20, verbose_name='协议')),
                ('metric', models.PositiveIntegerField(default=0, verbose_name='度量值')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('vrf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='assets.vrf', verbose_name='VRF')),
            ],
            options={
                'verbose_name': '路由',
                'verbose_name_plural': '路由',
                'db_table': 'configs_route',
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('interface', models.CharField(max_length=255, verbose_name='接口名')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='描述')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用')),
                ('mode', models.CharField(blank=True, choices=[('layer3', '三层接口'), ('access', 'Access'), ('hybrid', 'Hybrid'), ('trunk', 'Trunk')], max_length=20, null=True, verbose_name='接口模式')),
                ('vlans', models.JSONField(blank=True, default=dict, verbose_name='VLAN配置')),
                ('vrf', models.CharField(max_length=255, null=True, verbose_name='VRF')),
                ('type', models.CharField(max_length=255, null=True, verbose_name='接口类型')),
                ('combo_type', models.CharField(max_length=255, null=True, verbose_name='Combo类型')),
                ('ip_address', models.CharField(max_length=255, null=True, verbose_name='IP地址')),
                ('subnet_mask', models.CharField(max_length=255, null=True, verbose_name='子网掩码')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '网络接口',
                'verbose_name_plural': '网络接口',
                'db_table': 'devices_interface',
                'constraints': [models.UniqueConstraint(fields=('device', 'interface'), name='uni_device_interface')],
            },
        ),
        migrations.AddConstraint(
            model_name='vrf',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='uni_vrf_device_name'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('vrf', 'destination', 'nexthop'), name='uni_route_vrf_dst_nh'),
        ),
    ]
