# Generated by Django 6.1 on 2026-08-31 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_vlan_vrf_route_interface_vrf_uni_vrf_device_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('auth_type', models.CharField(choices=[('password', '密码认证'), ('ssh-key', 'SSH密钥'), ('both', '双因素认证')], default='password', max_length=20, verbose_name='认证方式')),
                ('privilege', models.CharField(choices=[('admin', '管理员'), ('operator', '操作员'), ('readonly', '只读用户')], default='admin', max_length=20, verbose_name='权限级别')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '设备管理用户',
                'verbose_name_plural': '设备管理用户',
                'db_table': 'devices_adminuser',
                'constraints': [models.UniqueConstraint(fields=('device', 'username'), name='uni_adminuser_device_username')],
            },
        ),
    ]
