# Generated by Django 6.1 on 2026-08-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_adminuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminUser',
            new_name='DeviceAccount',
        ),
        migrations.AlterModelOptions(
            name='deviceaccount',
            options={'verbose_name': '设备账号', 'verbose_name_plural': '设备账号'},
        ),
        migrations.RemoveConstraint(
            model_name='deviceaccount',
            name='uni_adminuser_device_username',
        ),
        migrations.AddConstraint(
            model_name='deviceaccount',
            constraint=models.UniqueConstraint(fields=('device', 'username'), name='uni_deviceaccount_device_username'),
        ),
        migrations.AlterModelTable(
            name='deviceaccount',
            table='devices_deviceaccount',
        ),
    ]
