# Generated by Django 6.1 on 2026-08-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_rename_adminuser_deviceaccount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cabinet',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='deviceconnection',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cabinet',
            constraint=models.UniqueConstraint(fields=('room', 'name'), name='uni_cabinet_room_name'),
        ),
        migrations.AddConstraint(
            model_name='deviceconnection',
            constraint=models.UniqueConstraint(fields=('device', 'account_type'), name='uni_deviceconn_device_account'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('datacenter', 'name'), name='uni_room_datacenter_name'),
        ),
        migrations.AlterModelTable(
            name='cabinet',
            table=None,
        ),
        migrations.AlterModelTable(
            name='datacenter',
            table=None,
        ),
        migrations.AlterModelTable(
            name='device',
            table=None,
        ),
        migrations.AlterModelTable(
            name='deviceaccount',
            table=None,
        ),
        migrations.AlterModelTable(
            name='deviceconfig',
            table=None,
        ),
        migrations.AlterModelTable(
            name='deviceconnection',
            table=None,
        ),
        migrations.AlterModelTable(
            name='devicemodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='interface',
            table=None,
        ),
        migrations.AlterModelTable(
            name='room',
            table=None,
        ),
        migrations.AlterModelTable(
            name='route',
            table=None,
        ),
        migrations.AlterModelTable(
            name='securityzone',
            table=None,
        ),
        migrations.AlterModelTable(
            name='vendor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='vlan',
            table=None,
        ),
        migrations.AlterModelTable(
            name='vrf',
            table=None,
        ),
    ]
