# Generated by Django 6.1 on 2026-08-31 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_cabinet_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='route',
            name='uni_route_vrf_dst_nh',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
