# Generated by Django 6.1 on 2026-08-31 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_remove_route_uni_route_vrf_dst_nh_delete_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interfaces', to='assets.vrf', verbose_name='VRF'),
        ),
    ]
