# Generated by Django 6.1 on 2026-08-31 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_interface_vrf'),
    ]

    operations = [
        migrations.CreateModel(
            name='NtpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server1', models.GenericIPAddressField(verbose_name='NTP服务器1')),
                ('server2', models.GenericIPAddressField(blank=True, null=True, verbose_name='NTP服务器2')),
                ('server3', models.GenericIPAddressField(blank=True, null=True, verbose_name='NTP服务器3')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='时区')),
                ('sync_interval', models.PositiveIntegerField(default=64, verbose_name='同步间隔(秒)')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用NTP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ntp_config', to='assets.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': 'NTP配置',
                'verbose_name_plural': 'NTP配置',
            },
        ),
        migrations.CreateModel(
            name='SnmpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('v1', 'v1'), ('v2c', 'v2c'), ('v3', 'v3')], default='v2c', max_length=10, verbose_name='SNMP版本')),
                ('community_read', models.CharField(blank=True, default='', max_length=100, verbose_name='读社区字符串')),
                ('community_write', models.CharField(blank=True, default='', max_length=100, verbose_name='写社区字符串')),
                ('port', models.PositiveIntegerField(default=161, verbose_name='监听端口')),
                ('trap_enabled', models.BooleanField(default=False, verbose_name='启用Trap')),
                ('trap_server', models.GenericIPAddressField(blank=True, null=True, verbose_name='Trap服务器')),
                ('trap_port', models.PositiveIntegerField(default=162, verbose_name='Trap端口')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用SNMP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_config', to='assets.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': 'SNMP配置',
                'verbose_name_plural': 'SNMP配置',
            },
        ),
        migrations.CreateModel(
            name='SyslogConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server1', models.GenericIPAddressField(verbose_name='日志服务器1')),
                ('server2', models.GenericIPAddressField(blank=True, null=True, verbose_name='日志服务器2')),
                ('port', models.PositiveIntegerField(default=514, verbose_name='端口')),
                ('facility', models.CharField(choices=[('local0', 'local0'), ('local1', 'local1'), ('local2', 'local2'), ('local3', 'local3'), ('local4', 'local4'), ('local5', 'local5'), ('local6', 'local6'), ('local7', 'local7')], default='local7', max_length=20, verbose_name='Facility')),
                ('level', models.CharField(choices=[('emergency', 'emergency'), ('alert', 'alert'), ('critical', 'critical'), ('error', 'error'), ('warning', 'warning'), ('notice', 'notice'), ('informational', 'informational'), ('debugging', 'debugging')], default='informational', max_length=20, verbose_name='日志级别')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用Syslog')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syslog_config', to='assets.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': 'Syslog配置',
                'verbose_name_plural': 'Syslog配置',
            },
        ),
    ]
