# Generated by Django 6.1 on 2026-09-01 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_ltmpoolmember_addressbook_gtmdatacenter_gtmpool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#3b82f6', max_length=7, verbose_name='颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=18, unique=True, verbose_name='网段 (CIDR)')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, verbose_name='默认网关')),
                ('vlan', models.CharField(blank=True, default='', max_length=20, verbose_name='VLAN')),
                ('vrf', models.CharField(blank=True, default='', max_length=50, verbose_name='所属VRF')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('datacenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subnets', to='assets.datacenter', verbose_name='数据中心')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assets.subnet', verbose_name='父网段')),
                ('security_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subnets', to='assets.securityzone', verbose_name='安全区')),
                ('tags', models.ManyToManyField(blank=True, related_name='subnets', to='assets.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '网段',
                'verbose_name_plural': '网段',
                'ordering': ('network',),
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('status', models.CharField(choices=[('used', '已使用'), ('reserved', '预留'), ('available', '可用')], default='used', max_length=20, verbose_name='状态')),
                ('interface', models.CharField(blank=True, default='', max_length=100, verbose_name='关联接口')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='assets.device', verbose_name='关联设备')),
                ('security_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='assets.securityzone', verbose_name='安全区')),
                ('subnet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='assets.subnet', verbose_name='所属网段')),
            ],
            options={
                'verbose_name': 'IP地址',
                'verbose_name_plural': 'IP地址',
                'ordering': ('ip_address',),
            },
        ),
    ]
