# Generated by Django 6.1 on 2026-09-02 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_tag_subnet_ipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=18, verbose_name='目的网段 (CIDR)')),
                ('nexthop', models.GenericIPAddressField(blank=True, null=True, verbose_name='下一跳地址')),
                ('interface', models.CharField(blank=True, default='', max_length=255, verbose_name='出接口')),
                ('protocol', models.CharField(choices=[('static', '静态'), ('connected', '直连'), ('ospf', 'OSPF'), ('bgp', 'BGP'), ('rip', 'RIP'), ('other', '其他')], default='static', max_length=20, verbose_name='协议')),
                ('metric', models.PositiveIntegerField(default=0, verbose_name='度量值')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('vrf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='assets.vrf', verbose_name='VRF')),
            ],
            options={
                'verbose_name': '路由',
                'verbose_name_plural': '路由',
                'constraints': [models.UniqueConstraint(fields=('vrf', 'destination', 'nexthop'), name='uni_route_vrf_dst_nh')],
            },
        ),
    ]
