# Generated by Django 6.1 on 2026-09-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='拓扑名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('graph_data', models.JSONField(default=dict, help_text='antv/g6 格式 JSON', verbose_name='图数据')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认拓扑')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网络拓扑',
                'verbose_name_plural': '网络拓扑',
                'ordering': ('-updated_at',),
            },
        ),
    ]
