# Generated by Django 6.1 on 2026-09-07 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_add_topology'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArpMac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan', models.CharField(blank=True, default='', max_length=50, verbose_name='VLAN')),
                ('interface', models.CharField(blank=True, default='', max_length=255, verbose_name='接口')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 地址')),
                ('mac_address', models.CharField(max_length=17, verbose_name='MAC 地址')),
                ('vendor', models.CharField(blank=True, default='', max_length=100, verbose_name='厂商')),
                ('arp_type', models.CharField(choices=[('dynamic', '动态'), ('static', '静态')], default='dynamic', max_length=20, verbose_name='ARP 类型')),
                ('learned_at', models.DateTimeField(blank=True, null=True, verbose_name='学习时间')),
                ('status', models.CharField(choices=[('normal', '正常'), ('aging', '老化中'), ('conflict', '冲突')], default='normal', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arp_mac_entries', to='assets.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': 'ARP/MAC',
                'verbose_name_plural': 'ARP/MAC',
                'ordering': ('-updated_at',),
                'constraints': [models.UniqueConstraint(fields=('device', 'ip_address', 'mac_address'), name='uni_arpmac_device_ip_mac')],
            },
        ),
    ]
